from __future__ import annotations

import re
from dataclasses import dataclass

from ..core.invoker import Capability, Field, SCALAR, STRING, ARRAY, HANDLE

                                        
_PROTO_SCALAR = {int: "int64", float: "double", str: "string", bool: "bool"}


def proto_type(f: Field) -> str:
    if f.kind == ARRAY:
        elem = _PROTO_SCALAR.get(f.elem_type or int, "int64")
        return f"repeated {elem}"
    if f.kind == HANDLE:
        return "int64"
    return _PROTO_SCALAR.get(f.py_type, "int64")


def pascal(name: str) -> str:
    """cJSON_GetObjectItem -> CJSONGetObjectItem (protobuf style)."""
    parts = re.split(r"[_\s]+", name)
    out = []
    for p in parts:
        if not p:
            continue
        out.append(p[0].upper() + p[1:] if not p.isupper() else p)
    s = "".join(out)
    return s[0].upper() + s[1:] if s else s


def needs_session(cap: Capability) -> bool:
    """True if the capability creates, consumes, or frees a handle."""
    if cap.lifecycle in ("creates", "borrows", "uses", "destroys"):
        return True
    return any(f.kind == HANDLE for f in cap.inputs + cap.outputs)


@dataclass
class ProtoFile:
    text: str
    services: list
    messages: list
    stateless: list                                           


def generate_proto(caps: list[Capability], package: str = "ferrule",
                   service: str = "Library") -> ProtoFile:
    """Emit a .proto for these capabilities."""
    L, messages, rpcs, stateless = [], [], [], []

    L.append('syntax = "proto3";')
    L.append("")
    L.append(f"package {package};")
    L.append("")
    L.append("// Generated by Ferrule from a verified capability spec.")
    L.append("// Handle ownership is enforced server-side: a BORROWED handle can be")
    L.append("// read but never freed (attempting it returns FAILED_PRECONDITION).")
    L.append("")

                                                                             
    L.append("// ---- session: handles are scoped to a session (a server-side handle table)")
    L.append("message OpenSessionRequest {}")
    L.append("message OpenSessionResponse { string session_id = 1; }")
    L.append("message CloseSessionRequest { string session_id = 1; }")
    L.append("message CloseSessionResponse {")
    L.append("  int64 released_handles = 1;   // handles still live when the session closed")
    L.append("}")
    L.append("")
    messages += ["OpenSessionRequest", "OpenSessionResponse",
                 "CloseSessionRequest", "CloseSessionResponse"]

                                                                            
    for cap in caps:
        Name = pascal(cap.name)
        sess = needs_session(cap)
        if not sess:
            stateless.append(cap.name)

        req, res = f"{Name}Request", f"{Name}Response"
        messages += [req, res]
        rpcs.append((Name, req, res, cap, sess))

        L.append(f"// {cap.doc}")
        if cap.lifecycle:
            note = f"lifecycle: {cap.lifecycle}"
            if cap.owner:
                note += f", owner: {cap.owner}"
            if cap.lifecycle == "borrows":
                note += "  (DO NOT free the returned handle)"
            L.append(f"// {note}")
        L.append(f"message {req} {{")
        n = 1
        if sess:
            L.append(f"  string session_id = {n};")
            n += 1
        for f in cap.inputs:
            L.append(f"  {proto_type(f)} {f.name} = {n};" +
                     (f"  // {f.doc}" if f.doc else ""))
            n += 1
        L.append("}")

        L.append(f"message {res} {{")
        n = 1
        if not cap.outputs:
            L.append("  // void")
        for f in cap.outputs:
            L.append(f"  {proto_type(f)} {f.name} = {n};" +
                     (f"  // {f.doc}" if f.doc else ""))
            n += 1
        L.append("}")
        L.append("")

                                                                             
    L.append(f"service {service} {{")
    L.append("  rpc OpenSession (OpenSessionRequest) returns (OpenSessionResponse);")
    L.append("  rpc CloseSession (CloseSessionRequest) returns (CloseSessionResponse);")
    for Name, req, res, cap, sess in rpcs:
        tag = "" if sess else "   // stateless: no session required"
        L.append(f"  rpc {Name} ({req}) returns ({res});{tag}")
    L.append("}")
    L.append("")

    return ProtoFile("\n".join(L), [service], messages, stateless)


                                                                            
                                                          
                                                                            
class SessionRegistry:
    """One HandleTable per session. Ownership rules are the core's, not ours."""

    def __init__(self):
        import itertools
        self._tables = {}
        self._ids = itertools.count(1)

    def open(self) -> str:
        from ..core.handles import HandleTable
        sid = f"s{next(self._ids)}"
        self._tables[sid] = HandleTable()
        return sid

    def table(self, sid: str):
        try:
            return self._tables[sid]
        except KeyError:
            raise KeyError(f"unknown session: {sid}") from None

    def close(self, sid: str) -> int:
        t = self._tables.pop(sid, None)
        if t is None:
            raise KeyError(f"unknown session: {sid}")
        return len(t)


def make_servicer(so_path: str, spec_path_or_spec, package: str = "ferrule"):
    """Build a gRPC servicer object whose methods call core capabilities.

    Capabilities are rebuilt PER SESSION so each session owns its handle table;
    stateless capabilities share one. Requires the generated _pb2_grpc stubs at
    runtime -- this returns a plain object with correctly-named methods that a
    generated servicer base can delegate to.
    """
    import ctypes

    from ..spec.io import load_yaml
    from ..core.invoker import build_capabilities
    from ..core.handles import HandleTable, OwnershipError

    spec = load_yaml(spec_path_or_spec) if isinstance(spec_path_or_spec, str) else spec_path_or_spec
    lib = ctypes.CDLL(so_path)
    sessions = SessionRegistry()
    shared_caps, refused = build_capabilities(lib, spec, HandleTable())
    by_name = {c.name: c for c in shared_caps}
    per_session_caps: dict = {}

    def caps_for(sid: str | None):
        if not sid:
            return by_name
        if sid not in per_session_caps:
            cs, _ = build_capabilities(lib, spec, sessions.table(sid))
            per_session_caps[sid] = {c.name: c for c in cs}
        return per_session_caps[sid]

    class Servicer:
        refused_functions = refused
        capability_names = [pascal(c.name) for c in shared_caps]                        

        def OpenSession(self, request, context=None):
            return {"session_id": sessions.open()}

        def CloseSession(self, request, context=None):
            sid = getattr(request, "session_id", None) or request["session_id"]
            per_session_caps.pop(sid, None)
            return {"released_handles": sessions.close(sid)}

        def call(self, name: str, fields: dict):
            """Invoke one capability. `fields` is the request message as a dict."""
            sid = fields.pop("session_id", None)
            cap = caps_for(sid).get(name)
            if cap is None:
                raise KeyError(f"unknown or refused capability: {name}")
            try:
                out = cap.invoke(**fields)
            except OwnershipError as e:
                                                                               
                raise PermissionError(str(e)) from None
            if cap.returns_mapping:
                return out if isinstance(out, dict) else {"result": out}
            return {} if not cap.outputs else {cap.outputs[0].name: out}

    s = Servicer()
                                                              
    for cap in shared_caps:
        def make(n):
            def m(request, context=None, _n=n):
                fields = request if isinstance(request, dict) else {
                    f.name: getattr(request, f.name) for f in by_name[_n].inputs
                    if hasattr(request, f.name)}
                if not isinstance(request, dict) and hasattr(request, "session_id"):
                    fields["session_id"] = request.session_id
                return s.call(_n, dict(fields))
            return m
        setattr(s, pascal(cap.name), make(cap.name))
    return s